AddonId: Barnite_fdcf35cc-edcd-4fc3-8640-bb037d3349fe
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/barnite0.1/Barnite_0_1.pext
    Changelog:
    - Initial release
    - MobyGames and PriceCharting support
    - English only
    - Manual entry only
  - Version: 0.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-31
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/barnite0.2/Barnite_0_2.pext
    Changelog:
    - Added Play-Asia and OGDB as data source
    - Added link to games pointing to the details page that the game was found on
  - Version: 0.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/barnite0.3/Barnite_0_3.pext
    Changelog:
    - Added settings
    - Added bol.com as data source
  - Version: 0.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/barnite0.4/Barnite_0_4.pext
    Changelog:
    - Fixed bol.com NullReferenceException when there are no results
    - Added retroplace as data source
  - Version: 0.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-05-24
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/barnite0.5/Barnite_0_5.pext
    Changelog:
    - Added RF Generation scraper
    - Added VGCollect scraper
    - Added text in settings suggesting use of Barcode to PC
