AddonId: BigFishLibrary
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.10
    ReleaseDate: 2023-12-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-12-03/BigFishLibrary_0_1.pext
    Changelog:
     - Initial release
  - Version: 0.1.1
    RequiredApiVersion: 6.10
    ReleaseDate: 2023-12-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-12-03/BigFishLibrary_0_1_1.pext
    Changelog:
     - Added missing Source field value for newly imported games
  - Version: 0.2
    RequiredApiVersion: 6.10
    ReleaseDate: 2024-04-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-04-08/BigFishLibrary_0_2.pext
    Changelog:
     - Added importing from Big Fish Games online account
     - Added metadata provider
  - Version: 0.3
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-05-20
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-05-20/BigFishLibrary_0_3.pext
    Changelog:
    - Fixed uninstalled/online game import
    - Added clickable notification that leads to settings when importing without being authenticated
    - Added store page link via metadata provider
  - Version: 0.3.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-06-22/BigFishLibrary_0_3_1.pext
    Changelog:
    - Fixed exception when no games are installed
  - Version: 0.4
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/BigFishLibrary_0_4.pext
    Changelog:
    - Fetching uninstalled games now uses the legacy API too, for older purchases
