AddonId: LegacyGamesLibrary_34c3178f-6e1d-4e27-8885-99d4f031b168
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/legacygames0.1/LegacyGamesLibrary_0_1.pext
    Changelog:
     - Initial release
  - Version: 0.1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/legacygames0.1.1/LegacyGamesLibrary_0_1_1.pext
    Changelog:
     - Fixed games not being able to launch if installed after import
  - Version: 0.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/legacygames0.2/LegacyGamesLibrary_0_2.pext
    Changelog:
     - Added Legacy Games client launching from Playnite
     - Made fetching installed games even more exception-proof