AddonId: BigFishLibrary
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.10
    ReleaseDate: 2023-12-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-12-03/BigFishLibrary_0_1.pext
    Changelog:
     - Initial release
  - Version: 0.1.1
    RequiredApiVersion: 6.10
    ReleaseDate: 2023-12-03
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-12-03/BigFishLibrary_0_1_1.pext
    Changelog:
     - Added missing Source field value for newly imported games
  - Version: 0.2
    RequiredApiVersion: 6.10
    ReleaseDate: 2024-04-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-04-08/BigFishLibrary_0_2.pext
    Changelog:
     - Added importing from Big Fish Games online account
     - Added metadata provider