AddonId: GamersGateLibrary
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-05-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/gamersgate0.1/GamersGateLibrary_0_1.pext
    Changelog:
     - Initial release
     - Manual game (un)install
     - Will open visible browser window to import library (to allow user to work around CAPTCHAs)