AddonId: IgnMetadata_6024e3a9-de7e-4848-9101-7a2f818e7e47
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-10-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/ign0.1/IgnMetadata_0_1.pext
    Changelog:
    - Initial release
  - Version: 0.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-10-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/ign0.2/IgnMetadata_0_2.pext
    Changelog:
    - Fixed possible exception in platform parsing
  - Version: 0.2.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/ign0.2.1/IgnMetadata_0_2_1.pext
    Changelog:
    - Fixed IGN API requests not returning anything
  - Version: 0.2.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-03-11
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-03-11/IgnMetadata_0_2_2.pext
    Changelog:
    - Fixed empty collection values not allowing fallback to other metadata providers
  - Version: 0.2.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-05-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-05-16/IgnMetadata_0_2_3.pext
    Changelog:
    - Small platform matching improvements
