AddonId: GOGMetadata
Packages:
  - Version: 0.1.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-09-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-09-22/GOGMetadata_0_1_1.pext
    Changelog:
    - Added metadata language default from Playnite language
  - Version: 0.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-01-10
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-01-10/GOGMetadata_0_2.pext
    Changelog:
    - Added packages (like Fallout 1) to search results
