AddonId: MobyGamesMetadata
Packages:
  - Version: 0.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-16/MobyGamesMetadata_0_2.pext
    Changelog:
     - Initial public release
     - Added genre settings
     - Added bulk genre assignment
  - Version: 0.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-18/MobyGamesMetadata_0_3.pext
    Changelog:
     - "Added image filtering options: minimum size and orientation"
     - "Added right-click options to genre settings to (mass-)set name overrides"
  - Version: 0.3.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-23/MobyGamesMetadata_0_3_1.pext
    Changelog:
     - Fixed links in game descriptions