AddonId: TvTropesMetadata
Packages:
  - Version: 0.4.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-06-22/TvTropesMetadata_0_4_2.pext
    Changelog:
    - Initial release
