AddonId: MobyGamesMetadata
Packages:
  - Version: 0.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-16/MobyGamesMetadata_0_2.pext
    Changelog:
     - Initial public release
     - Added genre settings
     - Added bulk genre assignment