AddonId: GOGMetadata
Packages:
  - Version: 0.1.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-09-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-09-22/GOGMetadata_0_1_1.pext
    Changelog:
    - Added metadata language default from Playnite language