AddonId: MobyGamesMetadata
Packages:
  - Version: 0.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-16/MobyGamesMetadata_0_2.pext
    Changelog:
     - Initial public release
     - Added genre settings
     - Added bulk genre assignment
  - Version: 0.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-18/MobyGamesMetadata_0_3.pext
    Changelog:
     - "Added image filtering options: minimum size and orientation"
     - "Added right-click options to genre settings to (mass-)set name overrides"
  - Version: 0.3.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-04-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-23/MobyGamesMetadata_0_3_1.pext
    Changelog:
     - Fixed links in game descriptions
  - Version: 0.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-05-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-05-16/MobyGamesMetadata_0_4.pext
    Changelog:
     - Made bulk game property import execution parallel (improves speed significantly)
     - Fixed bulk property assignment window overflowing screen bounds for some multi-monitor setups
     - Small platform matching improvements
     - Fixed link URL matching for games with old-style MobyGames links (no ID in the URL) and titles that start with a number
  - Version: 0.4.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-07-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-07-26/MobyGamesMetadata_0_4_1.pext
    Changelog:
     - Fixed title matching for automated metadata collection for games with alternate titles
  - Version: 0.4.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-09-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-09-22/MobyGamesMetadata_0_4_2.pext
    Changelog:
     - Fixed HTML entities in game names
     - Changed Windows Apps platform to Windows
     - Fixed games with numeric-only names fetching data from the wrong game
  - Version: 0.4.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-10-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-10-29/MobyGamesMetadata_0_4_3.pext
    Changelog:
     - Fixed HTML entities in game names (for real this time)
  - Version: 0.4.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-02-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-02-22/MobyGamesMetadata_0_4_4.pext
    Changelog:
     - Optimized game matching for bulk property import
  - Version: 0.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-05-20
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-05-20/MobyGamesMetadata_0_5.pext
    Changelog:
    - Added option to get release date for the game's platform(s) instead of earliest overall
    - Added ratings
    - Added developers and publishers
    - Updated available genres
    - Improved group field targeting
