AddonId: BigFishMetadata
Packages:
  - Version: 0.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-04-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-04-08/BigFishMetadata_0_2.pext
    Changelog:
    - Initial release (keeping version number with the library plugin)
